<?php

return [

    'options' => [
        'Pop',
        'Rock',
        'Acoustic',
        'Acoustic Pop',
        'OPM',
        'R&B',
        'Soul',
        'Jazz',
        'Blues',
        'Classical',
        'Country',
        'Folk',
        'Hip-Hop',
        'Rap',
        'EDM',
        'House',
        'Techno',
        'K-Pop',
        'Musical Theater',
        'Gospel',
        'Ballad',
        'Contemporary Dance',
        'Hip-Hop Dance',
        'Ballet',
        'Modern Dance',
        'Cultural / Traditional',
        'Street Dance',
        'Close-up Magic',
        'Stage Magic',
        'Illusion',
        'Stand-up Comedy',
        'Improv Comedy',
        'MC / Hosting',
        'Open Format DJ',
        'Club DJ',
        'Wedding DJ',
        'Live Band',
        'Cover Band',
        'Tribute Act',
        'Other',
    ],

];
